version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: api_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Rails API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/api_development
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: http://localhost:3001/auth/google/callback
      DEVISE_JWT_SECRET_KEY: ${DEVISE_JWT_SECRET_KEY}
      FRONTEND_URL: http://localhost:3001
      RAILS_ENV: development
    volumes:
      - ./api:/app
      - api_bundle:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        bundle exec rails db:create db:migrate &&
        bundle exec rails server -b 0.0.0.0 -p 3000
      "

  # React Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      VITE_API_URL: http://localhost:3000
      VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3001

volumes:
  postgres_data:
  api_bundle:
  client_node_modules: